name 'agent'
maintainer 'Andrzej Baldys'
maintainer_email 'andrzejbaldys1990@gmail.com'
license 'Apache-2.0'
description 'Installs/Configures agent'
long_description 'Installs/Configures agent'
version '0.1.10'
chef_version '>= 13.0'
supports 'ubuntu'
issues_url 'https://github.com/AndrzejBaldys/agent/issues'
source_url 'https://github.com/AndrzejBaldys/agent'
